<?php
/**
 * Manifest déclaratif des catégories et modules du plugin.
 *
 * Source de vérité unique : pour ajouter un module, on ajoute une entrée
 * ici + un fichier dans includes/modules/ ou assets/css/.
 *
 * Voir docs/superpowers/specs/2026-05-18-cordespace-admin-toggles-design.md §4.2-4.3
 */

defined( 'ABSPATH' ) || exit;

return [
	'categories' => [
		'mon-espace' => [ 'label' => 'Mon espace',           'icon' => '📋', 'order' => 10 ],
		'payments'   => [ 'label' => 'Paiements et crédits', 'icon' => '💰', 'order' => 20 ],
		'admin'        => [ 'label' => 'Outils admin',         'icon' => '🛠️', 'order' => 25 ],
		'waivers'      => [ 'label' => 'Waivers',              'icon' => '📝', 'order' => 27 ],
		'event-gating' => [ 'label' => "Événements à validation", 'icon' => '🔒', 'order' => 28 ],
		'styles'       => [ 'label' => 'Styles',               'icon' => '🎨', 'order' => 30 ],
	],

	'modules' => [
		'mon-espace.shortcode' => [
			'label'           => 'Page Mon espace',
			'description'     => 'L\'enveloppe de la page /mon-espace/ et son aiguillage cliente/prof. Désactiver ce module rend tout l\'écran dormant.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/mon-espace.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/mon-espace.php',
			'default_active'  => true,
		],
		'mon-espace.upcoming-qr' => [
			'label'           => 'QR cours à venir',
			'description'     => 'Affiche un QR code par cours réservé dans les 24h (vue cliente).',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/upcoming-qr.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/upcoming-qr.php',
			'default_active'  => true,
		],
		'mon-espace.credit-history' => [
			'label'           => 'Historique crédits',
			'description'     => 'Section historique MyCred dans la vue cliente (filtré pour ne montrer que les transactions de la personne connectée).',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/credit-history.php',
			'requires_plugin' => [ 'mycred/mycred.php' => 'MyCred' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/credit-history.php',
			'default_active'  => true,
		],
		'mon-espace.orders' => [
			'label'           => 'Mes commandes',
			'description'     => 'Section tableau des 10 dernières commandes WooCommerce dans la vue cliente, avec lien vers le détail natif WC pour chaque commande.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/orders.php',
			'requires_plugin' => [ 'woocommerce/woocommerce.php' => 'WooCommerce' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/orders.php',
			'default_active'  => true,
		],
		'mon-espace.teacher-presence' => [
			'label'           => 'Présence des élèves',
			'description'     => 'Toggle iOS-style pour marquer les élèves présent·es (vue prof) + endpoint REST + table SQL.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/teacher-presence.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/teacher-presence.php',
			'default_active'  => true,
		],
		'mon-espace.linked-accounts' => [
			'label'           => 'Comptes liés (bouton + champ admin)',
			'description'     => 'Permet à une même personne d\'avoir deux comptes WP (cliente + prof) liés et de basculer entre eux en 1 clic.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/linked-accounts.php',
			'requires_plugin' => [ 'user-switching/user-switching.php' => 'User Switching' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/linked-accounts.php',
			'default_active'  => true,
		],
		'mon-espace.amelia-role-context' => [
			'label'           => 'Découplage rôle Amelia ↔ contexte',
			'description'     => 'Évite que les profs avec rôle wpamelia-manager doivent se relogger sur le cabinet (auto-login WP_USER). Permet aussi à un administrateur de voir tous les events depuis wp-admin → Amelia (au lieu de seulement les siens en tant que prof). Modifie uniquement l\'objet user en mémoire, jamais la DB.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/amelia-role-context.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/amelia-role-context.php',
			'default_active'  => true,
		],
		'mon-espace.greeting-themes' => [
			'label'           => 'Thèmes de salutation personnalisés',
			'description'     => 'Permet d\'appliquer un fond décoratif (dinosaures, etc.) derrière le « Bonjour Prénom » de chaque utilisateur·trice. Configurable par profil dans wp-admin → Utilisateurs.',
			'category'        => 'mon-espace',
			'type'            => 'php',
			'file'            => 'includes/modules/greeting-themes.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/greeting-themes.php',
			'default_active'  => true,
		],
		'admin.reports' => [
			'label'           => 'Rapports de vente (Boutique / Cours / Salles)',
			'description'     => 'Page wp-admin → Cordespace → Rapports qui agrège les ventes WooCommerce sur une période choisie. 3 sections (Boutique, Cours Amelia, Salles Amelia) avec totaux + TPS/TVQ + export CSV. Calcule les vrais montants depuis WC (pas les 0$ d\'Amelia).',
			'category'        => 'admin',
			'type'            => 'php',
			'file'            => 'includes/modules/reports.php',
			'requires_plugin' => [ 'woocommerce/woocommerce.php' => 'WooCommerce' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/reports.php',
			'default_active'  => true,
		],
		'payments.prof-warning' => [
			'label'           => 'Bandeau d\'achat prof',
			'description'     => 'Avertit les profs au moment du panier qu\'iels sont sur leur compte enseignant·e.',
			'category'        => 'payments',
			'type'            => 'php',
			'file'            => 'includes/modules/prof-warning.php',
			'requires_plugin' => [
				'woocommerce/woocommerce.php' => 'WooCommerce',
				'ameliabooking/ameliabooking.php' => 'Amelia',
			],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/prof-warning.php',
			'default_active'  => true,
		],
		'waivers.schema' => [
			'label'           => 'Table waiver_signatures',
			'description'     => 'Crée et maintient la table append-only cordespace_waiver_signatures (1 ligne = 1 signature horodatée). Doit rester actif tant que des signatures existent.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-schema.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-schema.php',
			'default_active'  => true,
		],
		'waivers.cpt' => [
			'label'           => 'Contenu des waivers (CPT)',
			'description'     => 'Custom Post Type cordespace_waiver. Sous-menu Cordespace → Waivers pour éditer chaque décharge (titre + WYSIWYG + version). Bumper la version force tout le monde à re-signer.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-cpt.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-cpt.php',
			'default_active'  => true,
		],
		'waivers.store' => [
			'label'           => 'CRUD signatures (helpers)',
			'description'     => 'Helpers PHP utilisés par les autres modules waivers pour lire/écrire dans la table des signatures (has_signed_current, sign, history). Sans ce module, le gating et l\'historique ne peuvent pas fonctionner.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-store.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-store.php',
			'default_active'  => true,
		],
		'waivers.defaults' => [
			'label'           => 'Application par étiquettes Amelia',
			'description'     => 'Sur chaque waiver, choisis les étiquettes Amelia auxquelles il s\'applique. Tout événement portant une de ces étiquettes nécessite la signature. Metabox "Application par défaut" sur l\'écran d\'édition du waiver.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-defaults.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-defaults.php',
			'default_active'  => true,
		],
		'waivers.signing-page' => [
			'label'           => 'Page de signature',
			'description'     => 'URL /?cordespace_sign_waiver=1&waiver_id=X qui affiche le waiver + 2 cases d\'acceptation + bouton "Je signe". Sauvegarde la signature en DB. Indispensable pour que les gens puissent signer.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-signing-page.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-signing-page.php',
			'default_active'  => true,
		],
		'waivers.prof-badge' => [
			'label'           => 'Badge "WAIVER MANQUANT" (vue prof)',
			'description'     => 'Affiche un badge rouge à côté du nom des élèves qui n\'ont pas signé tous les waivers requis pour l\'événement, dans la vue prof "Présence des élèves". Filet de sécurité pour les paiements onSite qui bypass le gating WC checkout.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-prof-badge.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-prof-badge.php',
			'default_active'  => true,
		],
		'waivers.mon-espace' => [
			'label'           => 'Section "Mes waivers" dans Mon espace',
			'description'     => 'Affiche la liste des waivers (signés et à signer) dans la vue Mon espace côté client·e. S\'intègre dans le shortcode [cordespace_mon_espace] au slot `cordespace_mon_espace_section_client_waivers`. IP et navigateur restent en audit interne, jamais affichés au client.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-mon-espace.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-mon-espace.php',
			'default_active'  => true,
		],
		'waivers.checkout-warning' => [
			'label'           => 'Bandeau d\'avertissement waiver au checkout',
			'description'     => 'Affiche un bandeau rouge au-dessus du panier et du checkout si la cliente a un cours Amelia avec waiver requis non signé. NE BLOQUE PAS la commande (la signature est demandée après-coup via prompt post-achat + email reminder 48h avant l\'événement). Bouton "Signer maintenant" qui ramène vers la page de signature.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-checkout-warning.php',
			'requires_plugin' => [
				'woocommerce/woocommerce.php'     => 'WooCommerce',
				'ameliabooking/ameliabooking.php' => 'Amelia',
			],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-checkout-warning.php',
			'default_active'  => true,
		],
		'waivers.post-purchase-prompt' => [
			'label'           => 'Prompt post-achat (signer après commande)',
			'description'     => 'Affiche une banderole CTA orange « Signer maintenant » à 3 endroits : la page « Merci pour votre commande » (juste après le paiement), le dashboard /mon-compte/ (WC), et la page /mon-espace/ (Cordespace). La banderole liste les documents requis non signés pour les events Amelia upcoming, avec un bouton « Signer maintenant » par document.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-post-purchase-prompt.php',
			'requires_plugin' => [
				'woocommerce/woocommerce.php'     => 'WooCommerce',
				'ameliabooking/ameliabooking.php' => 'Amelia',
			],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-post-purchase-prompt.php',
			'default_active'  => true,
		],
		'waivers.email-reminder' => [
			'label'           => 'Email rappel 48h avant l\'événement',
			'description'     => 'WP cron quotidien (9h Montréal) qui envoie un email rappel aux client·es ayant un cours Amelia dans 36-60h et n\'ayant pas encore signé un document requis. Tracking custom-table pour ne JAMAIS envoyer deux fois le même email (1 par paire booking×document). Volume estimé : 5-20 emails/jour max.',
			'category'        => 'waivers',
			'type'            => 'php',
			'file'            => 'includes/modules/waivers-email-reminder.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/waivers-email-reminder.php',
			'default_active'  => true,
		],
		'event-gating.schema' => [
			'label'           => 'Table des approbations',
			'description'     => 'Crée et maintient la table wp_cordespace_event_type_approvals (event_type_id, user_id, status, notes, approved_at). 3 statuts possibles : pending / approved / rejected. Self-heal au admin_init.',
			'category'        => 'event-gating',
			'type'            => 'php',
			'file'            => 'includes/modules/event-gating-schema.php',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/event-gating-schema.php',
			'default_active'  => true,
		],
		'event-gating.cpt' => [
			'label'           => "CPT « Types d'événements à validation »",
			'description'     => "Custom Post Type cordespace_evtype pour définir les types d'événements qui nécessitent l'approbation admin (semi-privé, privé, atelier expert, etc.). Chaque type a un texte de bandeau, une whitelist d'étiquettes Amelia (matching auto avec les events), et une URL d'info. Sous-menu Cordespace → Événements à validation.",
			'category'        => 'event-gating',
			'type'            => 'php',
			'file'            => 'includes/modules/event-gating-cpt.php',
			'requires_plugin' => [ 'ameliabooking/ameliabooking.php' => 'Amelia' ],
			'github_path'     => 'plugins/cordespace-snippets/includes/modules/event-gating-cpt.php',
			'default_active'  => true,
		],
		'styles.wc-checkout-layout' => [
			'label'           => 'Marges WC panier / checkout',
			'description'     => 'Ajoute des marges latérales et un max-width sur les pages panier et checkout WooCommerce. Évite que le contenu colle aux bords du viewport sur grands écrans.',
			'category'        => 'styles',
			'type'            => 'css',
			'file'            => 'assets/css/wc-checkout-layout.css',
			'requires_plugin' => [ 'woocommerce/woocommerce.php' => 'WooCommerce' ],
			'github_path'     => 'plugins/cordespace-snippets/assets/css/wc-checkout-layout.css',
			'default_active'  => true,
		],
		'styles.menu-icon' => [
			'label'           => 'Icône bonhomme menu',
			'description'     => 'Remplace le texte « Mon espace » dans le menu par une icône blanche. Appliquer la classe CSS .cordespace-menu-icon sur l\'item de menu.',
			'category'        => 'styles',
			'type'            => 'css',
			'file'            => 'assets/css/menu-icon.css',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/assets/css/menu-icon.css',
			'default_active'  => true,
		],
		'styles.amelia-sidebar' => [
			'label'           => 'Masque sidebar Amelia',
			'description'     => 'Cache la barre latérale « Événements à venir » du calendrier Amelia.',
			'category'        => 'styles',
			'type'            => 'css',
			'file'            => 'assets/css/amelia-sidebar-cache.css',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/assets/css/amelia-sidebar-cache.css',
			'default_active'  => true,
		],
		'styles.callouts' => [
			'label'           => 'Callouts éditoriaux',
			'description'     => 'Style des encadrés .cordespace-note (variantes info / warn / ok) dans le contenu des pages.',
			'category'        => 'styles',
			'type'            => 'css',
			'file'            => 'assets/css/callouts.css',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/assets/css/callouts.css',
			'default_active'  => true,
		],
		'styles.footer-links' => [
			'label'           => 'Mise en forme du footer (couleurs, séparateur, spacing)',
			'description'     => 'Personnalisation visuelle du footer : (1) liens en lavande clair sur fond violet foncé avec blanc au hover ; (2) séparateur vertical entre les colonnes Français/English ; (3) spacing vertical réduit pour un footer compact ; (4) masque la mention "Politique de confidentialité" auto-ajoutée par WordPress (voir aussi Réglages → Confidentialité pour la retirer à la source).',
			'category'        => 'styles',
			'type'            => 'css',
			'file'            => 'assets/css/footer-links.css',
			'requires_plugin' => [],
			'github_path'     => 'plugins/cordespace-snippets/assets/css/footer-links.css',
			'default_active'  => true,
		],
	],
];
